import type { APIGatewayProxyHandler } from 'aws-lambda';
import { GetCommand, PutCommand, QueryCommand, UpdateCommand } from '@aws-sdk/lib-dynamodb';
import { v4 as uuidv4 } from 'uuid';
import { z } from 'zod';
import { db, ok, created, badRequest, unauthorized, forbidden, conflict, notFound, internalError, verifyToken, extractToken, registarAuditoria, logger } from '@dru-bos/shared';
import type { AuthContext } from '@dru-bos/shared';
const TABLE = process.env.RESTAURANTE_TABLE!;
async function auth(event: Parameters<APIGatewayProxyHandler>[0]): Promise<AuthContext | null> { const token = extractToken(event); return token ? verifyToken(token) : null; }
const MesaSchema = z.object({ nome: z.string().min(1).max(60), zona: z.string().max(60).optional(), lugares: z.number().int().positive().max(100).default(2) });
const PedidoSchema = z.object({ mesaId: z.string().uuid().optional(), tipo: z.enum(['mesa', 'balcao', 'takeaway']).default('mesa'), observacoes: z.string().max(500).optional() });
const LinhaSchema = z.object({ produtoId: z.string().uuid(), nome: z.string().min(1).max(150), quantidade: z.number().positive(), precoUnitario: z.number().nonnegative(), observacoes: z.string().max(300).optional() });
const EstadoSchema = z.object({ estado: z.enum(['aberto', 'em_preparacao', 'pronto', 'entregue', 'fechado', 'cancelado']) });
function base(empresaId: string, sk: string) { return { PK: `empresa#${empresaId}`, SK: sk }; }
function parse<T>(body: string | null | undefined, schema: z.ZodType<T>): T | null { try { const result = schema.safeParse(JSON.parse(body ?? '{}')); return result.success ? result.data : null; } catch { return null; } }
export const criarMesa: APIGatewayProxyHandler = async (event) => { const a = await auth(event); if (!a) return unauthorized(); if (a.role === 'viewer') return forbidden(); const data = parse(event.body, MesaSchema); if (!data) return badRequest('Dados invalidos'); const id = uuidv4(); const now = new Date().toISOString(); const item = { ...base(a.empresaId, `mesa#${id}`), tipo: 'mesa', id, empresaId: a.empresaId, ...data, estado: 'livre', createdAt: now, updatedAt: now }; try { await db.send(new PutCommand({ TableName: TABLE, Item: item, ConditionExpression: 'attribute_not_exists(PK)' })); return created(item); } catch (err) { logger.error('Erro ao criar mesa', { error: String(err) }); return internalError(); } };
export const listarMesas: APIGatewayProxyHandler = async (event) => { const a = await auth(event); if (!a) return unauthorized(); try { const r = await db.send(new QueryCommand({ TableName: TABLE, KeyConditionExpression: 'PK = :pk AND begins_with(SK, :prefix)', ExpressionAttributeValues: { ':pk': `empresa#${a.empresaId}`, ':prefix': 'mesa#' } })); return ok({ items: r.Items ?? [], total: r.Count ?? 0 }); } catch (err) { logger.error('Erro ao listar mesas', { error: String(err) }); return internalError(); } };
export const abrirPedido: APIGatewayProxyHandler = async (event) => { const a = await auth(event); if (!a) return unauthorized(); const data = parse(event.body, PedidoSchema); if (!data) return badRequest('Dados invalidos'); const id = uuidv4(); const now = new Date().toISOString(); const item = { ...base(a.empresaId, `pedido#${id}`), tipo: 'pedido', id, empresaId: a.empresaId, ...data, estado: 'aberto', total: 0, linhas: [], abertoPor: a.userId, createdAt: now, updatedAt: now }; try { await db.send(new PutCommand({ TableName: TABLE, Item: item, ConditionExpression: 'attribute_not_exists(PK)' })); if (data.mesaId) await db.send(new UpdateCommand({ TableName: TABLE, Key: base(a.empresaId, `mesa#${data.mesaId}`), UpdateExpression: 'SET estado = :ocupada, pedidoId = :pedido, updatedAt = :now', ConditionExpression: 'attribute_exists(PK) AND estado = :livre', ExpressionAttributeValues: { ':ocupada': 'ocupada', ':livre': 'livre', ':pedido': id, ':now': now } })); await registarAuditoria(a, 'abrir-pedido', 'pedido', id, { mesaId: data.mesaId }); return created(item); } catch (err) { logger.error('Erro ao abrir pedido', { error: String(err) }); return internalError(); } };
export const adicionarLinha: APIGatewayProxyHandler = async (event) => { const a = await auth(event); if (!a) return unauthorized(); const pedidoId = event.pathParameters?.id; if (!pedidoId) return badRequest('ID do pedido obrigatorio'); const data = parse(event.body, LinhaSchema); if (!data) return badRequest('Dados invalidos'); const p = await db.send(new GetCommand({ TableName: TABLE, Key: base(a.empresaId, `pedido#${pedidoId}`), ConsistentRead: true })); if (!p.Item || ['fechado', 'cancelado'].includes(String(p.Item.estado))) return conflict('Pedido inexistente ou encerrado'); const linha = { id: uuidv4(), ...data, total: Number((data.quantidade * data.precoUnitario).toFixed(2)) }; const linhas = [...((p.Item.linhas as Array<{ total: number }> | undefined) ?? []), linha]; const total = Number(linhas.reduce((s, l) => s + l.total, 0).toFixed(2)); try { await db.send(new UpdateCommand({ TableName: TABLE, Key: base(a.empresaId, `pedido#${pedidoId}`), UpdateExpression: 'SET linhas = :linhas, total = :total, updatedAt = :now', ConditionExpression: 'estado = :aberto OR estado = :prep', ExpressionAttributeValues: { ':linhas': linhas, ':total': total, ':now': new Date().toISOString(), ':aberto': 'aberto', ':prep': 'em_preparacao' } })); return ok({ pedidoId, linha, total }); } catch (err) { logger.error('Erro ao adicionar linha', { error: String(err) }); return internalError(); } };
export const alterarEstado: APIGatewayProxyHandler = async (event) => { const a = await auth(event); if (!a) return unauthorized(); const id = event.pathParameters?.id; const data = parse(event.body, EstadoSchema); if (!id || !data) return badRequest('Dados invalidos'); if (data.estado === 'fechado' && a.role === 'vendedor') return forbidden('Fecho requer gestor'); try { await db.send(new UpdateCommand({ TableName: TABLE, Key: base(a.empresaId, `pedido#${id}`), UpdateExpression: 'SET estado = :estado, actualizadoPor = :user, updatedAt = :now', ConditionExpression: 'attribute_exists(PK)', ExpressionAttributeValues: { ':estado': data.estado, ':user': a.userId, ':now': new Date().toISOString() } })); await registarAuditoria(a, 'alterar-estado-pedido', 'pedido', id, data); return ok({ id, estado: data.estado }); } catch (err) { logger.error('Erro ao alterar estado do pedido', { error: String(err) }); return notFound('Pedido nao encontrado'); } };
