Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: dru-bos-${sls:stage}
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      PasswordPolicy:
        MinimumLength: 8
        RequireUppercase: true
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: false
        TemporaryPasswordValidityDays: 7
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: empresa_id
          AttributeDataType: String
          Mutable: false
          StringAttributeConstraints:
            MaxLength: '36'
            MinLength: '36'
        - Name: role
          AttributeDataType: String
          Mutable: true
          StringAttributeConstraints:
            MaxLength: '20'
            MinLength: '4'
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UserPoolAddOns:
        AdvancedSecurityMode: AUDIT
      DeletionProtection: ${self:custom.cognitoDeletionProtection.${sls:stage}, 'INACTIVE'}
      Tags:
        - Key: Produto
          Value: dru-business-os
        - Key: Ambiente
          Value: ${sls:stage}

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: dru-bos-${sls:stage}-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      PreventUserExistenceErrors: ENABLED
      ReadAttributes:
        - email
        - name
        - custom:empresa_id
        - custom:role
      WriteAttributes:
        - email
        - name
        - custom:role

custom:
  cognitoDeletionProtection:
    prod: ACTIVE
    dev: INACTIVE
