Resources:
  FilesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: dru-bos-${sls:stage}-files-${aws:accountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: expire-temp-uploads
            Status: Enabled
            Prefix: temp/
            ExpirationInDays: 1
      Tags:
        - Key: Produto
          Value: dru-business-os
        - Key: Ambiente
          Value: ${sls:stage}
